apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongdb-deployment
  name: mongdb-deployment
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongdb-deployment
status:
  loadBalancer: {}
