apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: frontend
type: Opaque
data:
  API_KEY: RkpOMmZqMjlmaDIkQA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  app.properties: |
    - VAR_ONE=1
    - VAR_TWO=2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-ap
  namespace: frontend
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: app
          image: hello-world
          resources:
            requests:
              memory: "1000MiB"
              cpu: "0.5"
          envFrom:
            - secretRef:
                name: frontend-secret
          volumeMounts:
            - name: app-config
              mountPath: /etc/test_app/app.properties
      volumes:
        - name: app-config
          configMap:
            name: frontend-config
      nodeSelector:
        role: microservices
