apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
  namespace: frontend
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-frontend-service
  namespace: frontend
subsets:
  - addresses:
      - ip: 10.15.1.18
    ports:
      - port: 8081
