apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type:
  ports:
    - name: rest-api
      port:
      targetPort:
    - name: http
      port: 8080
      targetPort:
    - name: https
      port: 443
      targetPort: 443
  selector: {}
