{
 "title": "Frontend Service",
 "tags": [ "microservice" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Number of running kubernetes pods",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(<ENTER_METRIC_HERE>{pod=~\".*frontend.*\"})"
    }
   ]
  },
  {
   "title": "Pod Failures [last Hour]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(<ENTER_METRIC_HERE>{pod=~\".*insurance-transaction.*\", reason!=\"Completed\"}[1h]))"
    }
   ]
  },
  {
   "title": "Termination Reason",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (<ENTER_METRIC_HERE>{pod=~\".*insurance-transaction.*\", reason!=\"Completed\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "<ENTER_METRIC_HERE>:sum_rate{pod=~\".*insurance-transaction.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "<ENTER_METRIC_HERE>{pod=~\".*insurance-transaction.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate Over [$rate] of Requests Received & Records Inserted",
   "type": "graph",
   "description": "The rate of requests received and inserted via SQL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(increase(<ENTER_METRIC_HERE>[$rate]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum by (service)(increase(<ENTER_METRIC_HERE>[$rate]))",
     "legendFormat": "inserted"
    }
   ]
  },
  {
   "title": "Rate Over [$rate] of Errors by Error Type",
   "type": "graph",
   "description": "The rate of errors occurring by the type of error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(increase(<ENTER_METRIC_HERE>[$rate]))",
     "legendFormat": "request"
    },
    {
     "expr": "sum by (service)(increase(<ENTER_METRIC_HERE>[$rate]))",
     "legendFormat": "decode"
    },
    {
     "expr": "sum by (service)(increase(<ENTER_METRIC_HERE>[$rate]))",
     "legendFormat": "sql"
    }
   ]
  }
 ]
}